### PR TITLE
LICENSE: add title; collapse double newline at EOF

### PR DESCRIPTION
**Pull request by waldyrious**
The title is not legally mandated, but it's recommended in the license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license).

*This PR is part of a project to improve the consistency and visibility of the ISC license. See https://github.com/github/choosealicense.com/issues/377 for more details.*

### CODE REVIEW

**Comment by juliohm** [comment]
Thank you @waldyrious , since the title doesn't affect the legal aspect of it, I will leave it clean as it is.

**Comment by waldyrious** [comment]
I understand that perspective -- I recognized it in the opening sentence of the PR, after all :)

Still, I'd suggest you to reconsider, in light of the desire you've demonstrated [elsewhere](https://discourse.julialang.org/t/package-license/7109/10) to make this license more well-known: the title helps a great deal in making the license more visible. I think you might agree that the downsides of adding a single (quite relevant!) line are offset by the potential benefit that line can provide.

To give you an idea, in my efforts to disseminate the practice of including the title in the ISC license, multiple people have expressed surprise by finding out that the license they thought was MIT was instead ISC. You're right that these details don't matter for machines and for lawyers, but for regular human beings it plays a significant role in the social aspect of what makes a license more or less used.

**Comment by juliohm** [comment]
I agree that the it is important to educate people about it, but I just don't see the point of merging pull requests everywhere where the license is already being used. New packages can include the title if they want.

**Comment by waldyrious** [comment]
> I just don't see the point of merging pull requests everywhere where the license is already being used. New packages can include the title if they want.

I see it this way: If someone has decided to pick ISC for a new project, it's because they already know about it, so for them the title adds no value. Instead, the intended audience for this change is people who don't know about ISC, look at a package's existing license (e.g. to check for compliance requirements), learn that it is ISC, happen to like its conciseness, and decide to use it for their own project. Does this makes sense?

**Comment by waldyrious** [comment]
See https://github.com/juliohm/InverseDistanceWeighting.jl/pull/1 for additional context.

**Pull request closed without merging**
